### ISSUE TITLE
test images

### ISSUE THREAD

**Issue by khm159** [lorepas/fallen-people-detection#1]
hi. 

I executed the training code refer to READNE.md 

`python train_map.py conf_files/train_virtual.yaml`
    
Then I face this error. 

[ WARN:0@3341.611] global loadsave.cpp:248 cv::findDecoder imread_('test_imgs/split8_210.png'): can't open/read file: check file path/integrity

Could you tell me the type of test image you use when you run the above code?
It is difficult to know which dataset's image is just by the name split8_210.png.

**Comment by khm159** [comment]
I confirm that the test_imgs are test dataset of the EFPDS dataset.
That dataset can found in https://gram.web.uah.es/data/datasets/fpds/index.html

**Comment by lorepas** [comment]
Hello @khm159, I'm happy you've found the right test images. Maybe it's better to enanche my documentation, thank you for the hint.
